 name: Build and Push Docker Image

on:
  workflow_dispatch:

concurrency:
  group: docker-publish
  cancel-in-progress: true

env:
  CONTAINER_REGISTRY: "${{ secrets.CONTAINER_REGISTRY }}"
  DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
  IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Build
        run: docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:ahmedelrouby .

      - name: Docker Login
        run: echo "${{ secrets.PASSWORD }}" | docker login $CONTAINER_REGISTRY -u "$DOCKER_USERNAME" --password-stdin

      - name: Docker Push
        run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:ahmedelrouby
